"""update for reset passowrd.

Revision ID: 3db1dc2199d4
Revises: f3f574193f68
Create Date: 2024-08-02 17:34:45.730936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db1dc2199d4'
down_revision = 'f3f574193f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_reset_token_expiration')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
